#!/usr/bin/env bash
# This script ensures Nginx is running and listening on port 80
# and opens port 80 in the firewall if necessary
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
