#!/usr/bin/env bash

# This Bash script displays a list of currently running processes
# It shows all processes for all users including those which might not have a TTY
# Displays in a user-oriented format
# Shows process hierarchy

ps aux f
