#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop

# Counter variable to keep track of iterations
counter=0

# Loop until the counter reaches 10
until [ $counter -ge 10 ]
do
	# Print "Best School"
	echo "Best School"
	# Increment the counter
	((counter++))
done
