#!/usr/bin/env bash

# This script displays "Best School" 10 times
# but shows "Hi" on a new line for the 9th iteration

# Counter variable to keep track of iterations
counter=0

# Loop until the counter reaches 10
while [ $counter -lt 10 ]
do
	# Check if it's the 9th iteration
	if [ $counter -eq 9 ]
	then
		# Print "Hi"
		echo "Hi"
	fi
	# Print "Best School"
	echo "Best School"
	# Increment the counter
	((counter++))
done
